micronaut:
  application:
    name: mn05
  #security:
    #authentication: session
netty:
  default:
    allocator:
      max-order: 3

hello:
  world:
    message: "Hello message!"
goodbye:
  world:
    message: "Goodbye message!"

