micronaut:
  application:
    name: mn05

micronaut:
  security:
    enabled: true
    authentication: session

    session:
      enabled: true

    endpoints:
      login:
        enabled: true
      logout:
        enabled: true

netty:
  default:
    allocator:
      max-order: 3


identity-store:
  users:
    alice: alice@1
    bob: bob@2
    charlie: charlie@3

  roles:
    alice: ADMIN
    bob: VIEW
    charlie: VIEW

hello:
  world:
    message: "Hello message!"
goodbye:
  world:
    message: "Goodbye message!"

